//! Keyed BLAKE2b feature hashing — byte-exact parity with
//! `context_m.util.h64` (digest_size=8, key = seed as 8 LE bytes,
//! result read little-endian).

use blake2::digest::consts::U8;
use blake2::digest::{FixedOutput, KeyInit, Update};
use blake2::Blake2bMac;
use pyo3::prelude::*;

#[pyfunction]
#[pyo3(signature = (feature, seed = 0))]
pub fn h64(feature: &str, seed: i64) -> u64 {
    let key = (seed as u64).to_le_bytes();
    let mut hasher = <Blake2bMac<U8> as KeyInit>::new_from_slice(&key)
        .expect("8-byte blake2b output is valid");
    hasher.update(feature.as_bytes());
    let out = hasher.finalize_fixed();
    let mut b = [0u8; 8];
    b.copy_from_slice(&out);
    u64::from_le_bytes(b)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_vector() {
        // parity vectors generated by the Python reference
        // (context_m.util.h64)
        assert_eq!(h64("perm:S", 0x0C0FFEE), 2404016449295660810);
        assert_eq!(h64("role:R", 0x0C0FFEE), 2520869231761063392);
        assert_eq!(h64("entity:Alice", 0), 13907527500564060562);
    }
}
